import 'package:flutter/material.dart';

/// Color schemes for the app
class ColorSchemes {
  /// Light color scheme
  static final ColorScheme lightColorScheme = ColorScheme(
    brightness: Brightness.light,
    primary: const Color(0xFF0070F3),
    onPrimary: Colors.white,
    primaryContainer: const Color(0xFFD1E4FF),
    onPrimaryContainer: const Color(0xFF001D36),
    secondary: const Color(0xFF7928CA),
    onSecondary: Colors.white,
    secondaryContainer: const Color(0xFFF3E8FF),
    onSecondaryContainer: const Color(0xFF2E0052),
    tertiary: const Color(0xFF006875),
    onTertiary: Colors.white,
    tertiaryContainer: const Color(0xFF95F0FF),
    onTertiaryContainer: const Color(0xFF001F24),
    error: const Color(0xFFBA1A1A),
    onError: Colors.white,
    errorContainer: const Color(0xFFFFDAD6),
    onErrorContainer: const Color(0xFF410002),
    surface: const Color(0xFFFFFFFF),
    onSurface: const Color(0xFF1A1A1A),
    onSurfaceVariant: const Color(0xFF44474E),
    outline: const Color(0xFFE1E1E1),
    outlineVariant: const Color(0xFFEEEEEE),
    shadow: const Color(0xFF000000),
    scrim: const Color(0xFF000000),
    inverseSurface: const Color(0xFF303030),
    onInverseSurface: const Color(0xFFF5F5F5),
    inversePrimary: const Color(0xFF9ECAFF),
    surfaceTint: const Color(0xFF0070F3),
    surfaceContainerLowest: const Color(0xFFFFFFFF),
    surfaceContainerLow: const Color(0xFFF8F9FA),
    surfaceContainer: const Color(0xFFF2F2F2),
    surfaceContainerHigh: const Color(0xFFECECEC),
    surfaceContainerHighest: const Color(0xFFE6E6E6),
  );

  /// Dark color scheme
  static final ColorScheme darkColorScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: const Color(0xFF9ECAFF),
    onPrimary: const Color(0xFF003258),
    primaryContainer: const Color(0xFF00497D),
    onPrimaryContainer: const Color(0xFFD1E4FF),
    secondary: const Color(0xFFD0BCFF),
    onSecondary: const Color(0xFF381E72),
    secondaryContainer: const Color(0xFF4F378B),
    onSecondaryContainer: const Color(0xFFEADDFF),
    tertiary: const Color(0xFF4FD8EB),
    onTertiary: const Color(0xFF00363D),
    tertiaryContainer: const Color(0xFF004F58),
    onTertiaryContainer: const Color(0xFF95F0FF),
    error: const Color(0xFFFFB4AB),
    onError: const Color(0xFF690005),
    errorContainer: const Color(0xFF93000A),
    onErrorContainer: const Color(0xFFFFDAD6),
    surface: const Color(0xFF1E1E1E),
    onSurface: const Color(0xFFE3E3E3),
    onSurfaceVariant: const Color(0xFFC4C7D0),
    outline: const Color(0xFF8E9099),
    outlineVariant: const Color(0xFF444746),
    shadow: const Color(0xFF000000),
    scrim: const Color(0xFF000000),
    inverseSurface: const Color(0xFFF5F5F5),
    onInverseSurface: const Color(0xFF303030),
    inversePrimary: const Color(0xFF0070F3),
    surfaceTint: const Color(0xFF9ECAFF),
    surfaceContainerLowest: const Color(0xFF121212),
    surfaceContainerLow: const Color(0xFF1E1E1E),
    surfaceContainer: const Color(0xFF2A2A2A),
    surfaceContainerHigh: const Color(0xFF363636),
    surfaceContainerHighest: const Color(0xFF424242),
  );
}
