name: Linux Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
          flutter pub get

      - name: Enable Linux desktop
        run: flutter config --enable-linux-desktop

      - name: Build Linux application
        run: flutter build linux --release

      - name: Install packaging tools
        run: sudo apt-get install -y debhelper fakeroot

      - name: Create .deb package
        run: |
          mkdir -p packaging/linux/debian/DEBIAN
          mkdir -p packaging/linux/debian/usr/local/bin
          mkdir -p packaging/linux/debian/usr/share/applications
          mkdir -p packaging/linux/debian/usr/share/icons/hicolor/512x512/apps

          # Copy executable
          cp -r build/linux/x64/release/bundle/* packaging/linux/debian/usr/local/bin/

          # Create desktop entry
          cat > packaging/linux/debian/usr/share/applications/pinboard-app.desktop << EOF
          [Desktop Entry]
          Name=Pinboard App
          Comment=A modern pinboard application
          Exec=/usr/local/bin/pinboard_app
          Icon=pinboard-app
          Terminal=false
          Type=Application
          Categories=Utility;
          EOF

          # Copy icon
          cp assets/icon/app_icon.png packaging/linux/debian/usr/share/icons/hicolor/512x512/apps/pinboard-app.png

          # Create control file
          cat > packaging/linux/debian/DEBIAN/control << EOF
          Package: pinboard-app
          Version: 1.0.0
          Section: utils
          Priority: optional
          Architecture: amd64
          Maintainer: Pinboard App Team <support@example.com>
          Description: A modern pinboard application
           Pinboard App is a feature-rich application for organizing notes, links,
           and other content in a visual pinboard format.
          EOF

          # Build the package
          fakeroot dpkg-deb --build packaging/linux/debian
          mv packaging/linux/debian.deb pinboard-app_1.0.0_amd64.deb

      - name: Upload Linux .deb package
        uses: actions/upload-artifact@v3
        with:
          name: pinboard-app-linux
          path: pinboard-app_1.0.0_amd64.deb
          retention-days: 7
