name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Build Windows executable
        run: flutter build windows --release

      - name: Download Inno Setup
        run: |
          Invoke-WebRequest -Uri "https://files.jrsoftware.org/is/6/innosetup-6.2.2.exe" -OutFile "innosetup-installer.exe"
          Start-Process -FilePath "innosetup-installer.exe" -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-" -Wait

      - name: Prepare for installer creation
        run: |
          mkdir -Force windows\build\windows\installer

      - name: Create installer with Inno Setup
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" windows/inno_setup.iss

      - name: Upload Windows installer
        uses: actions/upload-artifact@v4
        with:
          name: pinboard-app-windows
          path: windows/build/windows/installer/pinboard_app_setup.exe
          retention-days: 7
